<?php

namespace WebshopBundle\Repository;

/**
 * FactuurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactuurRepository extends \Doctrine\ORM\EntityRepository
{
}
