<?php

namespace WebshopBundle\Repository;

/**
 * ProductenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductenRepository extends \Doctrine\ORM\EntityRepository
{
}
