<?php

namespace WebshopBundle\Repository;

/**
 * RegelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegelRepository extends \Doctrine\ORM\EntityRepository
{
}
